### ISSUE TITLE
Cross-server teleportation will only bring the player to the spawn point of the server, not to the location of the target player.

### ISSUE THREAD

**Issue by lipind** [savagedevllc/BungeeTpa#2]
[BungeeTp] Plugin BungeeTp v1.0.3 generated an exception whilst handling plugin message
java.lang.NullPointerException: null
at net.savagedev.tpa.common.messaging.AbstractMessenger.handleIncomingMessage(AbstractMessenger.java:36) ~[?:?]
at net.savagedev.tpa.spigot.messenger.SpigotPluginMessenger.onPluginMessageReceived(SpigotPluginMessenger.java:40) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2760) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
at java.lang.Thread.run(Thread.java:829) [?:?]
——————————————————————————————————
Players cannot teleport to another player, they will only teleport to the server spawn

I did not see velocity version 1.0.3 in the download, so I am using BungeTpa velocity 1.0.1
and BungeeTpa-bridge-spigot-1.0.3

**Comment by SavageAvocado** [comment]
A lot changed in the messaging protocol between those versions, so 1.0.1 won't work with 1.0.3 at all. I thought I published a release here will all platforms for 1.0.3, I guess I forgot lol. I'll make a release for 1.0.3 with the velocity plugin for you in a bit. Done: https://github.com/savagedevllc/BungeeTpa/releases/tag/1.0.3
